/**
 * Fake Email Detection Service
 * 
 * This service detects and blocks fake, temporary, and disposable email addresses
 * during user registration to ensure only legitimate users can register.
 */

class FakeEmailDetector {
  constructor() {
    // List of common fake/temporary email domains
    this.fakeDomains = new Set([
      // Temporary email services
      '10minutemail.com',
      '10minutemail.net',
      '20minutemail.com',
      '2prong.com',
      'temp-mail.org',
      'tempmail.net',
      'guerrillamail.com',
      'guerrillamail.net',
      'guerrillamail.org',
      'guerrillamailblock.com',
      'sharklasers.com',
      'grr.la',
      'guerrillamail.de',
      'guerrillamail.biz',
      'guerrillamail.info',
      'mailinator.com',
      'maildrop.cc',
      'throwaway.email',
      'yopmail.com',
      'yopmail.net',
      'cool.fr.nf',
      'jetable.fr.nf',
      'nospam.ze.tc',
      'nomail.xl.cx',
      'mega.zik.dj',
      'speed.1s.fr',
      'courriel.fr.nf',
      'moncourrier.fr.nf',
      'monemail.fr.nf',
      'monmail.fr.nf',
      'hide.biz.st',
      'mymail.infos.st',
      'emeil.tk',
      'emeil.ga',
      'emeil.ml',
      'emeil.cf',
      'tmail.ws',
      'tmailinator.com',
      'trash-mail.com',
      'trashmail.com',
      'trashmail.org',
      'trashmail.net',
      'spamgourmet.com',
      'spamgourmet.net',
      'spamgourmet.org',
      'spamhole.com',
      'spaml.com',
      'spamex.com',
      'pookmail.com',
      'sneakemail.com',
      'snkmail.com',
      'anonymbox.com',
      'anonbox.net',
      'mytrashmail.com',
      'wh4f.org',
      'gishpuppy.com',
      'deadaddress.com',
      'sa.ge',
      'dispostable.com',
      'getnada.com',
      'fakemail.net',
      'mintemail.com',
      'emailondeck.com',
      'emailsensei.com',
      'tempail.com',
      'tempemail.com',
      'tempr.email',
      'temp.email',
      'email.tmmad.com',
      'tmmad.com',
      'maildax.com',
      'tempinbox.com',
      'tempmailaddress.com',
      'emailfake.com',
      'fakeemailgenerator.com',
      'fake-email.ml',
      'fake-mail.ml',
      'fake-mail.ga',
      'fake-mail.cf',
      'fake-mail.tk',
      'fakemailgenerator.com',
      'tempmail24.com',
      'tempmail.email',
      'tempmail10.com',
      'tempmail.us',
      'minute-mail.cf',
      'minute-mail.ga',
      'minute-mail.gq',
      'minute-mail.ml',
      'minute-mail.tk',
      'minuteinbox.com',
      'minutemailbox.com',
      'mohmal.com',
      'mohmal.in',
      'mohmal.tech',
      'crazymailing.com',
      'panzar.info',
      'valemail.net',
      'kurzepost.de',
      'wegwerfmail.de',
      'wegwerfmail.net',
      'wegwerfmail.org',
      'zehnminutenmail.de',
      'zehnminutenmail.ch',
      'zehnminutenmail.at',
      '0-mail.com',
      '0815.ru',
      '0clickemail.com',
      '0wnd.net',
      '0wnd.org',
      '10mail.org',
      '123-m.com',
      '1chuan.com',
      '1pad.de',
      '20email.eu',
      '2fdgdfgdfgdf.tk',
      '2prong.com',
      '30minutemail.com',
      '33mail.com',
      '3d-game.com',
      '4warding.com',
      '4warding.net',
      '4warding.org',
      '60minutemail.com',
      '675hosting.com',
      '675hosting.net',
      '675hosting.org',
      '6ip.us',
      '6paq.com',
      '6url.com',
      '75hosting.com',
      '75hosting.net',
      '75hosting.org',
      '7tags.com',
      '9ox.net',
      'a-bc.net',
      'abyssmail.com',
      'afrobacon.com',
      'ajaxapp.net',
      'amilegit.com',
      'amiri.net',
      'amiriindustrial.com',
      'anonmails.de',
      'anonymail.dk',
      'antichef.com',
      'antichef.net',
      'antireg.ru',
      'antispam.de',
      'antispammail.de',
      'armyspy.com',
      'artman-conception.com',
      'azmeil.tk',
      'baxomale.ht.cx',
      'beddly.com',
      'beefmilk.com',
      'bigprofessor.so',
      'bigstring.com',
      'binkmail.com',
      'bio-muesli.net',
      'bobmail.info',
      'bodhi.lawlita.com',
      'bofthew.com',
      'bootybay.de',
      'boun.cr',
      'bouncr.com',
      'boxformail.in',
      'boximail.com',
      'brefmail.com',
      'brennendesreich.de',
      'broadbandninja.com',
      'bsnow.net',
      'bspamfree.org',
      'bugmenot.com',
      'bumpymail.com',
      'burnthespam.info',
      'burstmail.info',
      'buymoreplays.com',
      'byom.de',
      'c2.hu',
      'card.zp.ua',
      'casualdx.com',
      'centermail.com',
      'centermail.net',
      'chammy.info',
      'childsavetoys.com',
      'chogmail.com',
      'choicemail1.com',
      'chong-mail.com',
      'clixser.com',
      'cmail.net',
      'cmail.org',
      'coldemail.info',
      'cool.fr.nf',
      'correo.blogos.net',
      'cosmorph.com',
      'courriel.fr.nf',
      'courrieltemporaire.com',
      'crapmail.org',
      'cust.in',
      'd3p.dk',
      'dacoolest.com',
      'dandikmail.com',
      'dayrep.com',
      'dcemail.com',
      'deadaddress.com',
      'deadspam.com',
      'delikkt.de',
      'despam.it',
      'despammed.com',
      'devnullmail.com',
      'dfgh.net',
      'digitalsanctuary.com',
      'dingbone.com',
      'disposableaddress.com',
      'disposableemailaddresses.com',
      'disposableinbox.com',
      'dispose.it',
      'dispostable.com',
      'dm.w3internet.com',
      'dodgeit.com',
      'dodgit.com',
      'dontreg.com',
      'dontsendmespam.de',
      'drdrb.net',
      'dump-email.info',
      'dumpandjunk.com',
      'dumpmail.de',
      'dumpyemail.com',
      'e-mail.com',
      'e-mail.org',
      'e4ward.com',
      'easytrashmail.com',
      'einrot.com',
      'einrot.de',
      'eintagsmail.de',
      'email60.com',
      'emaildienst.de',
      'emailias.com',
      'emailinfive.com',
      'emailmiser.com',
      'emailsensei.com',
      'emailspam.cf',
      'emailspam.ga',
      'emailspam.gq',
      'emailspam.ml',
      'emailspam.tk',
      'emailtemporanea.com',
      'emailtemporanea.net',
      'emailtemporario.com.br',
      'emailto.de',
      'emailwarden.com',
      'emailx.at.hm',
      'emailxfer.com',
      'emeil.in',
      'emeil.ir',
      'emz.net',
      'enterto.com',
      'ephemail.net',
      'etranquil.com',
      'etranquil.net',
      'etranquil.org',
      'explodemail.com',
      'express.net.ua',
      'eyepaste.com',
      'facebook-email.cf',
      'facebook-email.ga',
      'facebook-email.ml',
      'facebook-email.tk',
      'facebookmail.gq',
      'facebookmail.ml',
      'fake-box.com',
      'fake-email.pp.ua',
      'fake-mail.cf',
      'fake-mail.ga',
      'fake-mail.ml',
      'fake-mail.tk',
      'fakeinbox.com',
      'fakeinformation.com',
      'fakemail.fr',
      'fakemailgenerator.com',
      'fakemailz.com',
      'fammix.com',
      'fansworldwide.de',
      'fantasymail.de',
      'fastacura.com',
      'fastchevy.com',
      'fastchrysler.com',
      'fastkawasaki.com',
      'fastmazda.com',
      'fastmitsubishi.com',
      'fastnissan.com',
      'fastsubaru.com',
      'fastsuzuki.com',
      'fasttoyota.com',
      'fastyamaha.com',
      'fightallspam.com',
      'filzmail.com',
      'fivemail.de',
      'fixmail.tk',
      'fizmail.com',
      'fleckens.hu',
      'fr33mail.info',
      'frapmail.com',
      'freegmail.cf',
      'freegmail.ga',
      'freegmail.ml',
      'freegmail.tk',
      'freemails.cf',
      'freemails.ga',
      'freemails.ml',
      'freundin.ru',
      'friendlymail.co.uk',
      'front14.org',
      'fuckingduh.com',
      'fudgerub.com',
      'fux0ringduh.com',
      'garliclife.com',
      'gehensiemirnichtaufdensack.de',
      'geschent.biz',
      'get-mail.cf',
      'get-mail.ga',
      'get-mail.ml',
      'get-mail.tk',
      'get1mail.com',
      'get2mail.fr',
      'getairmail.com',
      'getmails.eu',
      'getonemail.com',
      'getonemail.net',
      'ghosttexter.de',
      'girlsundertheinfluence.com',
      'gishpuppy.com',
      'gmail-temp.com',
      'goemailgo.com',
      'gotmail.net',
      'gotmail.org',
      'gotti.otherinbox.com',
      'great-host.in',
      'greensloth.com',
      'grr.la',
      'gsrv.co.uk',
      'guerillamail.biz',
      'guerillamail.com',
      'guerillamail.de',
      'guerillamail.info',
      'guerillamail.net',
      'guerillamail.org',
      'guerrillamail.biz',
      'guerrillamail.com',
      'guerrillamail.de',
      'guerrillamail.info',
      'guerrillamail.net',
      'guerrillamail.org',
      'guerrillamailblock.com',
      'h.mintemail.com',
      'h8s.org',
      'haltospam.com',
      'harakirimail.com',
      'hat-geld.de',
      'hatespam.org',
      'hellodream.mobi',
      'herp.in',
      'hidemail.de',
      'hidzz.com',
      'hmamail.com',
      'hochsitze.com',
      'hopemail.biz',
      'hotpop.com',
      'hulapla.de',
      'ieatspam.eu',
      'ieatspam.info',
      'ieh-mail.de',
      'ikbenspamvrij.nl',
      'imails.info',
      'inbax.tk',
      'inbox.si',
      'inboxalias.com',
      'inboxclean.com',
      'inboxclean.org',
      'inboxproxy.com',
      'incognitomail.com',
      'incognitomail.net',
      'incognitomail.org',
      'infocom.zp.ua',
      'instant-mail.de',
      'ip6.li',
      'irish2me.com',
      'iroid.com',
      'iwi.net',
      'jetable.com',
      'jetable.fr.nf',
      'jetable.net',
      'jetable.org',
      'jnxjn.com',
      'jourrapide.com',
      'jsrsolutions.com',
      'junk1e.com',
      'junkmail.ga',
      'junkmail.gq',
      'kasmail.com',
      'kaspop.com',
      'keepmymail.com',
      'killmail.com',
      'killmail.net',
      'kir.ch.tc',
      'klassmaster.com',
      'klzlk.com',
      'kook.ml',
      'koszmail.pl',
      'kurzepost.de',
      'l33r.eu',
      'labetteraverouge.at',
      'lackmail.net',
      'lags.us',
      'laoeq.com',
      'lawlita.com',
      'lazyinbox.com',
      'letthemeatspam.com',
      'lhsdv.com',
      'lifebyfood.com',
      'link2mail.net',
      'litedrop.com',
      'loadby.us',
      'login-email.cf',
      'login-email.ga',
      'login-email.ml',
      'login-email.tk',
      'lol.ovpn.to',
      'lolfreak.net',
      'lookugly.com',
      'lopl.co.cc',
      'lortemail.dk',
      'lostmail.com',
      'loveable.de',
      'lpshield.com',
      'luckymail.org',
      'm21.cc',
      'mail-filter.com',
      'mail-temporaire.fr',
      'mail.by',
      'mail.mezimages.net',
      'mail.zp.ua',
      'mail114.net',
      'mail1a.de',
      'mail21.cc',
      'mail2rss.org',
      'mail333.com',
      'mail4trash.com',
      'mailbidon.com',
      'mailblocks.com',
      'mailbucket.org',
      'mailcat.biz',
      'mailcatch.com',
      'mailde.de',
      'mailde.info',
      'maildrop.cc',
      'maildrop.cf',
      'maildrop.ga',
      'maildrop.gq',
      'maildrop.ml',
      'maildu.de',
      'maildx.com',
      'maileater.com',
      'mailed.ro',
      'maileimer.de',
      'mailexpire.com',
      'mailfa.tk',
      'mailforspam.com',
      'mailfreeonline.com',
      'mailguard.me',
      'mailhazard.com',
      'mailhazard.us',
      'mailhz.me',
      'mailin8r.com',
      'mailinatar.com',
      'mailinatar.tk',
      'mailinator.com',
      'mailinator.gq',
      'mailinator.net',
      'mailinator.org',
      'mailinator.us',
      'mailinator2.com',
      'mailismagic.com',
      'mailita.tk',
      'mailjunk.cf',
      'mailjunk.ga',
      'mailjunk.gq',
      'mailjunk.ml',
      'mailjunk.tk',
      'mailmate.com',
      'mailmetrash.com',
      'mailmoat.com',
      'mailms.com',
      'mailnator.com',
      'mailnesia.com',
      'mailnull.com',
      'mailorg.org',
      'mailpick.biz',
      'mailproxsy.com',
      'mailquack.com',
      'mailrock.biz',
      'mailsac.com',
      'mailscrap.com',
      'mailshell.com',
      'mailsiphon.com',
      'mailtemp.info',
      'mailtome.de',
      'mailtothis.com',
      'mailtrash.net',
      'mailtv.net',
      'mailtv.tv',
      'mailzilla.com',
      'mailzilla.org',
      'makemetheking.com',
      'malahov.de',
      'manifestgenerator.com',
      'manybrain.com',
      'mbx.cc',
      'mega.zik.dj',
      'meinspamschutz.de',
      'meltmail.com',
      'messagebeamer.de',
      'mezimages.net',
      'mierdamail.com',
      'migmail.pl',
      'mintemail.com',
      'mjukglass.nu',
      'mobi.web.id',
      'mobileninja.co.uk',
      'moburl.com',
      'moncourrier.fr.nf',
      'monemail.fr.nf',
      'monmail.fr.nf',
      'monumentmail.com',
      'msa.minsmail.com',
      'mt2009.com',
      'mx0.wwwnew.eu',
      'my10minutemail.com',
      'mycard.net.ua',
      'mycleaninbox.net',
      'myemailboxy.com',
      'mymail-in.net',
      'mymail.infos.st',
      'mymailoasis.com',
      'mynetstore.de',
      'mypacks.net',
      'mypartyclip.de',
      'myphantomemail.com',
      'myspaceinc.com',
      'myspaceinc.net',
      'myspaceinc.org',
      'myspacepimpedup.com',
      'myspamless.com',
      'mytrashmail.com',
      'n1nja.org',
      'nabuma.com',
      'nalaka.net',
      'neomailbox.com',
      'nepwk.com',
      'nervmich.net',
      'nervtmich.net',
      'netmails.com',
      'netmails.net',
      'netzidiot.de',
      'neverbox.com',
      'nice-4u.com',
      'nincsmail.com',
      'nincsmail.hu',
      'nnh.com',
      'no-spam.ws',
      'nobugmail.com',
      'nobulk.com',
      'noclickemail.com',
      'nogmailspam.info',
      'nomail.xl.cx',
      'nomail2me.com',
      'nomorespamemails.com',
      'nonspam.eu',
      'nonspammer.de',
      'noref.in',
      'nospam.ze.tc',
      'nospam4.us',
      'nospamfor.us',
      'nospammail.net',
      'notmailinator.com',
      'notsharingmy.info',
      'nowhere.org',
      'nowmymail.com',
      'ntlhelp.net',
      'nullbox.info',
      'nurfuerspam.de',
      'nwldx.com',
      'objectmail.com',
      'obobbo.com',
      'odnorazovoe.ru',
      'one-time.email',
      'oneoffemail.com',
      'onewaymail.com',
      'onlatedotcom.info',
      'online.ms',
      'oopi.org',
      'opayq.com',
      'ordinaryamerican.net',
      'otherinbox.com',
      'ovpn.to',
      'owlpic.com',
      'oxuta.com',
      'p.2-e.eu',
      'paplease.com',
      'pcusers.otherinbox.com',
      'pepbot.com',
      'pfui.ru',
      'pimpedupmyspace.com',
      'pjkdo.com',
      'plexolan.de',
      'politikerclub.de',
      'polyfaust.com',
      'pooae.com',
      'pookmail.com',
      'privacy.net',
      'privatdemail.net',
      'procsports.com',
      'proxymail.eu',
      'prtnx.com',
      'prtz.eu',
      'punkass.com',
      'putthisinyourspamdatabase.com',
      'pwrby.com',
      'qasti.com',
      'qisdo.com',
      'qisoa.com',
      'qq.com',
      'quickinbox.com',
      'rcpt.at',
      'reallymymail.com',
      'receiveee.chickenkiller.com',
      'receiveee.com',
      'recursor.net',
      'regbypass.com',
      'regbypass.comsafe-mail.net',
      'rejectmail.com',
      'rhyta.com',
      'rmqkr.net',
      'royal.net',
      'rppkn.com',
      'rtrtr.com',
      'rubbishmail.com',
      's0ny.net',
      'safe-mail.net',
      'safersignup.de',
      'safetymail.info',
      'safetypost.de',
      'sandelf.de',
      'saynotospams.com',
      'schafmail.de',
      'schrott-email.de',
      'secretemail.de',
      'secure-mail.biz',
      'selfdestructingmail.com',
      'selfdestructingmail.org',
      'sendspamhere.de',
      'senseless-entertainment.com',
      'services391.com',
      'sharedmailbox.org',
      'sharklasers.com',
      'shieldemail.com',
      'shiftmail.com',
      'shitmail.me',
      'shitmail.org',
      'shitware.nl',
      'shmeriously.com',
      'shortmail.net',
      'sibmail.com',
      'sify.com',
      'sillymail.org',
      'sinnlos-mail.de',
      'siteposter.net',
      'skeefmail.com',
      'slaskpost.se',
      'slopsbox.com',
      'slushmail.com',
      'smashmail.de',
      'smellfear.com',
      'snakemail.com',
      'sneakemail.com',
      'sneakmail.de',
      'snkmail.com',
      'sofimail.com',
      'solvemail.info',
      'sogetthis.com',
      'soodonims.com',
      'spam.la',
      'spam.su',
      'spam4.me',
      'spamail.de',
      'spamarrest.com',
      'spambob.com',
      'spambob.net',
      'spambob.org',
      'spambog.com',
      'spambog.de',
      'spambog.net',
      'spambog.ru',
      'spambox.info',
      'spambox.irishspringtours.com',
      'spambox.us',
      'spamcannon.com',
      'spamcannon.net',
      'spamcon.org',
      'spamcorptastic.com',
      'spamcowboy.com',
      'spamcowboy.net',
      'spamcowboy.org',
      'spamday.com',
      'spamex.com',
      'spamfree24.com',
      'spamfree24.de',
      'spamfree24.eu',
      'spamfree24.net',
      'spamfree24.org',
      'spamgoes.com',
      'spamgourmet.com',
      'spamgourmet.net',
      'spamgourmet.org',
      'spamherelots.com',
      'spamhereplease.com',
      'spamhole.com',
      'spami.spam.co.za',
      'spamify.com',
      'spaminator.de',
      'spamkill.info',
      'spaml.com',
      'spaml.de',
      'spammotel.com',
      'spamobox.com',
      'spamoff.de',
      'spamslicer.com',
      'spamspot.com',
      'spamstack.net',
      'spamthis.co.uk',
      'spamthisplease.com',
      'spamtrail.com',
      'spamtroll.net',
      'speed.1s.fr',
      'spoofmail.de',
      'stuffmail.de',
      'super-auswahl.de',
      'supergreatmail.com',
      'supermailer.jp',
      'superrito.com',
      'superstachel.de',
      'suremail.info',
      'talkinator.com',
      'teewars.org',
      'teleworm.com',
      'teleworm.us',
      'temp-mail.de',
      'temp-mail.org',
      'temp-mail.ru',
      'temp.emeraldwebhosting.com',
      'tempail.com',
      'tempalias.com',
      'tempe-mail.com',
      'tempemail.biz',
      'tempemail.com',
      'tempinbox.co.uk',
      'tempinbox.com',
      'tempmail.it',
      'tempmail2.com',
      'tempmaildemo.com',
      'tempmailer.com',
      'tempmailer.de',
      'tempmailid.com',
      'tempr.email',
      'tempymail.com',
      'thanksnospam.info',
      'thankyou2010.com',
      'thc.st',
      'thecloudindex.com',
      'thisisnotmyrealemail.com',
      'thismail.net',
      'throwam.com',
      'throwawayemailaddresses.com',
      'tilien.com',
      'tittbit.in',
      'tizi.com',
      'tmail.ws',
      'tmailinator.com',
      'toomail.biz',
      'topranklist.de',
      'tormail.net',
      'tormail.org',
      'tradermail.info',
      'trash-amil.com',
      'trash-mail.at',
      'trash-mail.com',
      'trash-mail.de',
      'trash2009.com',
      'trashdevil.com',
      'trashdevil.de',
      'trashemail.de',
      'trashmail.at',
      'trashmail.com',
      'trashmail.de',
      'trashmail.me',
      'trashmail.net',
      'trashmail.org',
      'trashmail.ws',
      'trashmailer.com',
      'trashymail.com',
      'trashymail.net',
      'trbvm.com',
      'trialmail.de',
      'trillianpro.com',
      'tryalert.com',
      'turual.com',
      'twinmail.de',
      'twoweirdtricks.com',
      'txtadvertise.com',
      'tyldd.com',
      'uggsrock.com',
      'umail.net',
      'uacro.com',
      'ultracheap.com',
      'unmail.ru',
      'upliftnow.com',
      'uplipht.com',
      'uroid.com',
      'us.af',
      'venompen.com',
      'veryrealemail.com',
      'viditag.com',
      'viewcastmedia.com',
      'viewcastmedia.net',
      'viewcastmedia.org',
      'vomoto.com',
      'vubby.com',
      'walala.org',
      'walkmail.net',
      'webemail.me',
      'webm4il.info',
      'weg-werf-email.de',
      'wegwerf-email-addressen.de',
      'wegwerf-emails.de',
      'wegwerfadresse.de',
      'wegwerfemail.com',
      'wegwerfemail.de',
      'wegwerfmail.de',
      'wegwerfmail.info',
      'wegwerfmail.net',
      'wegwerfmail.org',
      'wetrainbayarea.com',
      'wetrainbayarea.org',
      'wh4f.org',
      'whatiaas.com',
      'whatpaas.com',
      'whatsaas.com',
      'whopy.com',
      'whyspam.me',
      'willhackforfood.biz',
      'willselldrugs.com',
      'wmail.cf',
      'wolfmails.com',
      'wronghead.com',
      'wuzup.net',
      'wuzupmail.net',
      'www.e4ward.com',
      'www.gishpuppy.com',
      'www.mailinator.com',
      'wwwnew.eu',
      'x.ip6.li',
      'xagloo.com',
      'xemaps.com',
      'xents.com',
      'xmaily.com',
      'xoxy.net',
      'yep.it',
      'yogamaven.com',
      'yomail.info',
      'yopmail.com',
      'yopmail.fr',
      'yopmail.net',
      'yourdomain.com',
      'ypmail.webredirect.org',
      'yuurok.com',
      'yzbid.com',
      'zehnminutenmail.de',
      'zetmail.com',
      'zoemail.net',
      'zoemail.org',
      'zomg.info',
      'zxcv.com',
      'zxcvbnm.com',
      'zzz.com'
    ]);

    // Common patterns in fake emails
    this.suspiciousPatterns = [
      /^[a-z0-9]{32}@/i, // 32 character random string
      /^test.*@/i,        // starts with "test"
      /^fake.*@/i,        // starts with "fake"
      /^temp.*@/i,        // starts with "temp"
      /^spam.*@/i,        // starts with "spam"
      /^trash.*@/i,       // starts with "trash"
      /^junk.*@/i,        // starts with "junk"
      /^throw.*@/i,       // starts with "throw"
      /^dispos.*@/i,      // starts with "dispos"
      /^mailinator.*@/i,  // contains "mailinator"
      /^guerrilla.*@/i,   // contains "guerrilla"
      /.*\+.*@/,          // contains plus sign (gmail trick)
      /.*\d{10,}.*@/      // contains 10+ consecutive digits
    ];

    // Legitimate domains that should be allowed
    this.legitimateDomains = new Set([
      'gmail.com',
      'yahoo.com',
      'hotmail.com',
      'outlook.com',
      'live.com',
      'msn.com',
      'icloud.com',
      'me.com',
      'mac.com',
      'aol.com',
      'protonmail.com',
      'proton.me',
      'tutanota.com',
      'zoho.com',
      'yandex.com',
      'mail.ru',
      'fastmail.com',
      'hushmail.com',
      'rocketmail.com',
      'rediffmail.com',
      'inbox.com',
      'gmx.com',
      'gmx.net',
      'web.de',
      't-online.de',
      'freenet.de',
      'comsats.edu.pk',
      'student.comsats.edu.pk',
      'ciit.net.pk',
      'edu.pk',
      'gov.pk',
      'org.pk',
      'net.pk',
      'com.pk'
    ]);
  }

  /**
   * Check if an email address is fake or suspicious
   * @param {string} email - Email address to check
   * @returns {Object} - Result object with isFake, reason, confidence
   */
  checkEmail(email) {
    if (!email || typeof email !== 'string') {
      return {
        isFake: true,
        reason: 'Invalid email format',
        confidence: 100
      };
    }

    // Normalize email
    const normalizedEmail = email.toLowerCase().trim();
    
    // Basic email format validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(normalizedEmail)) {
      return {
        isFake: true,
        reason: 'Invalid email format',
        confidence: 100
      };
    }

    const [localPart, domain] = normalizedEmail.split('@');

    // If it's a known legitimate domain, mark as safe (skip pattern checks)
    if (this.legitimateDomains.has(domain)) {
      return {
        isFake: false,
        reason: 'Legitimate email domain',
        confidence: 90
      };
    }

    // Check against fake domains list
    if (this.fakeDomains.has(domain)) {
      return {
        isFake: true,
        reason: `Fake/temporary email domain: ${domain}`,
        confidence: 95
      };
    }

    // Check against suspicious patterns (only for non-legitimate domains)
    for (const pattern of this.suspiciousPatterns) {
      if (pattern.test(normalizedEmail)) {
        return {
          isFake: true,
          reason: `Suspicious email pattern detected`,
          confidence: 80
        };
      }
    }

    // Check for very short domains (often fake)
    if (domain.length < 4) {
      return {
        isFake: true,
        reason: 'Domain name too short (likely fake)',
        confidence: 70
      };
    }

    // Check for domains with only numbers
    if (/^\d+\.\w+$/.test(domain)) {
      return {
        isFake: true,
        reason: 'Numeric domain (likely fake)',
        confidence: 75
      };
    }

    // Check for domains ending with suspicious TLDs
    const suspiciousTlds = ['.tk', '.ml', '.ga', '.cf', '.gq'];
    const domainTld = '.' + domain.split('.').pop();
    if (suspiciousTlds.includes(domainTld)) {
      return {
        isFake: true,
        reason: `Suspicious TLD: ${domainTld}`,
        confidence: 65
      };
    }

    // For other domains, perform additional checks
    
    // Check if domain has multiple consecutive dots
    if (domain.includes('..')) {
      return {
        isFake: true,
        reason: 'Invalid domain format (consecutive dots)',
        confidence: 85
      };
    }

    // Check for very long local parts (often generated)
    if (localPart.length > 50) {
      return {
        isFake: true,
        reason: 'Suspiciously long email address',
        confidence: 60
      };
    }

    // Check for random-looking local parts
    if (/^[a-z0-9]{20,}$/i.test(localPart)) {
      return {
        isFake: true,
        reason: 'Random-looking email address',
        confidence: 70
      };
    }

    // If no red flags, consider it legitimate but with lower confidence
    return {
      isFake: false,
      reason: 'Email appears legitimate',
      confidence: 60
    };
  }

  /**
   * Add a domain to the fake domains list
   * @param {string} domain - Domain to add
   */
  addFakeDomain(domain) {
    this.fakeDomains.add(domain.toLowerCase());
  }

  /**
   * Remove a domain from the fake domains list
   * @param {string} domain - Domain to remove
   */
  removeFakeDomain(domain) {
    this.fakeDomains.delete(domain.toLowerCase());
  }

  /**
   * Add a domain to the legitimate domains list
   * @param {string} domain - Domain to add
   */
  addLegitimeDomain(domain) {
    this.legitimateDomains.add(domain.toLowerCase());
  }

  /**
   * Get statistics about the detector
   * @returns {Object} - Statistics object
   */
  getStats() {
    return {
      fakeDomains: this.fakeDomains.size,
      legitimateDomains: this.legitimateDomains.size,
      suspiciousPatterns: this.suspiciousPatterns.length
    };
  }
}

module.exports = FakeEmailDetector;