const express = require('express');
const router = express.Router();
const { auth, hasRole } = require('../middleware/auth');
const {
  upload,
  getEligibleStudentsForAppraisal,
  createInternshipAppraisal,
  getCompanyAppraisals,
  getSupervisorAppraisals,
  getAppraisalById,
  updateAppraisalStatus,
  deleteAppraisal
} = require('../controllers/internshipAppraisalController');

// Test route
router.get('/test', (req, res) => {
  res.json({ message: 'Internship appraisal routes working' });
});

// Get eligible students for appraisal (hired students) - Company only
router.get('/eligible-students', auth, hasRole('company'), getEligibleStudentsForAppraisal);

// Create internship appraisal with file upload - Company only
router.post('/create', auth, hasRole('company'), upload.array('attachments', 5), createInternshipAppraisal);

// Get company's appraisal reports - Company only
router.get('/company', auth, hasRole('company'), getCompanyAppraisals);

// Get supervisor's appraisals - Supervisor only
router.get('/supervisor', auth, hasRole('supervisor'), getSupervisorAppraisals);

// Download appraisal PDF - Both company and supervisor
router.get('/:appraisalId/pdf', auth, async (req, res) => {
  try {
    const { appraisalId } = req.params;
    const InternshipAppraisal = require('../models/InternshipAppraisal');
    const appraisal = await InternshipAppraisal.findById(appraisalId);
    
    if (!appraisal) {
      return res.status(404).json({ success: false, message: 'Appraisal not found' });
    }
    
    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument({ margin: 72 });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="internship_appraisal_${appraisal.studentName.replace(/\s+/g, '_')}.pdf"`);
    
    doc.pipe(res);
    
    // Header Bar
    doc.rect(0, 0, doc.page.width, 60).fill('#2563eb');
    doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold')
       .text('COMSATS INTERNSHIP PORTAL', 0, 20, { align: 'center' });
    
    doc.y = 100;
    
    // Title
    doc.fillColor('#111827').fontSize(18).font('Helvetica-Bold')
       .text('INTERNSHIP APPRAISAL REPORT', { align: 'center' });
    
    doc.y += 30;
    
    // Information Table
    const tableData = [
      ['Student Name', appraisal.studentName],
      ['Roll Number', appraisal.rollNumber || 'N/A'],
      ['Company Name', appraisal.companyName],
      ['Internship Title', appraisal.internshipTitle],
      ['Duration', appraisal.duration],
      ['Overall Performance', appraisal.overallPerformance],
      ['Rating', `${appraisal.rating}/10`],
      ['Recommendation', appraisal.recommendation],
      ['Submitted By', `${appraisal.submittedBy} (${appraisal.submittedByEmail})`],
      ['Submission Date', new Date(appraisal.submissionDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })]
    ];
    
    tableData.forEach(([label, value]) => {
      const y = doc.y;
      doc.rect(72, y, 180, 25).fill('#f3f4f6').stroke('#e5e7eb');
      doc.rect(252, y, 270, 25).fill('#f9fafb').stroke('#e5e7eb');
      
      doc.fillColor('#374151').fontSize(11).font('Helvetica-Bold')
         .text(label, 82, y + 8);
      doc.fillColor('#111827').fontSize(11).font('Helvetica')
         .text(value, 262, y + 8);
      
      doc.y = y + 25;
    });
    
    doc.y += 20;
    
    // Key Strengths Section
    doc.fillColor('#111827').fontSize(14).font('Helvetica-Bold')
       .text('Key Strengths', { underline: true });
    doc.y += 10;
    doc.rect(72, doc.y, 450, 60).fill('#f0fdf4').stroke('#bbf7d0');
    doc.fillColor('#166534').fontSize(11).font('Helvetica')
       .text(appraisal.keyStrengths, 82, doc.y + 10, { width: 430, align: 'justify' });
    
    doc.y += 80;
    
    // Areas for Improvement Section
    doc.fillColor('#111827').fontSize(14).font('Helvetica-Bold')
       .text('Areas for Improvement', { underline: true });
    doc.y += 10;
    doc.rect(72, doc.y, 450, 60).fill('#fffbeb').stroke('#fde68a');
    doc.fillColor('#92400e').fontSize(11).font('Helvetica')
       .text(appraisal.areasForImprovement, 82, doc.y + 10, { width: 430, align: 'justify' });
    
    doc.y += 80;
    
    // Comments & Feedback Section
    doc.fillColor('#111827').fontSize(14).font('Helvetica-Bold')
       .text('Comments & Feedback', { underline: true });
    doc.y += 10;
    doc.rect(72, doc.y, 450, 80).fill('#f9fafb').stroke('#e5e7eb');
    doc.fillColor('#374151').fontSize(11).font('Helvetica')
       .text(appraisal.commentsAndFeedback, 82, doc.y + 10, { width: 430, align: 'justify' });
    
    // Footer
    const footerY = doc.page.height - 100;
    doc.rect(72, footerY, 450, 30).fill('#f3f4f6');
    doc.fillColor('#6b7280').fontSize(9).font('Helvetica')
       .text('Generated by COMSATS Internship Portal', 82, footerY + 10)
       .text(`${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} | Page 1 | ID: ${appraisal._id.toString().slice(-8)}`, 350, footerY + 10);
    
    doc.end();
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate PDF' });
  }
});

// Get appraisal by ID - Company only
router.get('/:appraisalId', auth, hasRole('company'), getAppraisalById);

// Update appraisal status - Company only
router.patch('/:appraisalId/status', auth, hasRole('company'), updateAppraisalStatus);

// Delete appraisal - Company only
router.delete('/:appraisalId', auth, hasRole('company'), deleteAppraisal);

module.exports = router;
