const mongoose = require('mongoose');
const User = require('../models/User');
const CompanyProfile = require('../models/CompanyProfile');

const companies = [
  {
    companyName: "TechCorp Solutions",
    industry: "Software Development",
    about: "Leading software development company specializing in enterprise solutions and digital transformation.",
    vision: "To be the global leader in innovative technology solutions that transform businesses.",
    mission: "Delivering cutting-edge software solutions that drive business growth and efficiency.",
    foundedYear: 2015,
    employeeCount: "201-500",
    headquartersLocation: "Islamabad",
    website: "https://techcorp.com",
    companyEmail: "hr@techcorp.com",
    contactPerson: { name: "Ahmed Khan", phone: "0321-1234567" },
    specialties: ["Web Development", "Mobile Apps", "Cloud Solutions", "AI/ML"],
    socialMedia: { linkedin: "https://linkedin.com/company/techcorp", twitter: "https://twitter.com/techcorp" }
  },
  {
    companyName: "Digital Innovations Ltd",
    industry: "Information Technology",
    about: "Pioneering digital transformation through innovative IT solutions and consulting services.",
    vision: "Empowering businesses through digital excellence and technological innovation.",
    mission: "To provide world-class IT solutions that enable our clients to achieve their digital goals.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Karachi",
    website: "https://digitalinnovations.pk",
    companyEmail: "careers@digitalinnovations.pk",
    contactPerson: { name: "Fatima Ali", phone: "0300-9876543" },
    specialties: ["Digital Marketing", "E-commerce", "CRM Systems", "Data Analytics"],
    socialMedia: { linkedin: "https://linkedin.com/company/digitalinnovations", twitter: "https://twitter.com/digiinnovations" }
  },
  {
    companyName: "CodeCraft Studios",
    industry: "Software Development",
    about: "Creative software studio focused on building beautiful and functional applications.",
    vision: "Crafting digital experiences that inspire and engage users worldwide.",
    mission: "To create innovative software solutions that solve real-world problems with elegance.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://codecraft.studio",
    companyEmail: "hello@codecraft.studio",
    contactPerson: { name: "Hassan Malik", phone: "0333-5555555" },
    specialties: ["React Development", "Node.js", "UI/UX Design", "Mobile Development"],
    socialMedia: { linkedin: "https://linkedin.com/company/codecraft", twitter: "https://twitter.com/codecraftstudio" }
  },
  {
    companyName: "DataFlow Analytics",
    industry: "Data Science",
    about: "Advanced data analytics and business intelligence solutions for modern enterprises.",
    vision: "Transforming data into actionable insights for better business decisions.",
    mission: "Empowering organizations with data-driven solutions and predictive analytics.",
    foundedYear: 2017,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://dataflow.pk",
    companyEmail: "info@dataflow.pk",
    contactPerson: { name: "Dr. Sarah Ahmed", phone: "0345-7777777" },
    specialties: ["Machine Learning", "Big Data", "Business Intelligence", "Python"],
    socialMedia: { linkedin: "https://linkedin.com/company/dataflow", twitter: "https://twitter.com/dataflowpk" }
  },
  {
    companyName: "CloudTech Systems",
    industry: "Cloud Computing",
    about: "Leading cloud infrastructure and DevOps solutions provider in Pakistan.",
    vision: "Enabling seamless cloud transformation for businesses of all sizes.",
    mission: "Delivering reliable, scalable, and secure cloud solutions.",
    foundedYear: 2016,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://cloudtech.pk",
    companyEmail: "careers@cloudtech.pk",
    contactPerson: { name: "Ali Raza", phone: "0312-8888888" },
    specialties: ["AWS", "Azure", "DevOps", "Kubernetes"],
    socialMedia: { linkedin: "https://linkedin.com/company/cloudtech", twitter: "https://twitter.com/cloudtechpk" }
  },
  {
    companyName: "MobileTech Solutions",
    industry: "Mobile Development",
    about: "Specialized mobile app development company creating innovative mobile experiences.",
    vision: "Leading the mobile revolution with cutting-edge app solutions.",
    mission: "Building mobile applications that enhance user experiences and drive business growth.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://mobiletech.pk",
    companyEmail: "hr@mobiletech.pk",
    contactPerson: { name: "Zara Khan", phone: "0301-4444444" },
    specialties: ["React Native", "Flutter", "iOS Development", "Android Development"],
    socialMedia: { linkedin: "https://linkedin.com/company/mobiletech", twitter: "https://twitter.com/mobiletechpk" }
  },
  {
    companyName: "CyberSecure Pro",
    industry: "Cybersecurity",
    about: "Comprehensive cybersecurity solutions protecting businesses from digital threats.",
    vision: "Creating a secure digital world for businesses and individuals.",
    mission: "Providing robust cybersecurity solutions to protect digital assets.",
    foundedYear: 2014,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://cybersecure.pk",
    companyEmail: "security@cybersecure.pk",
    contactPerson: { name: "Omar Sheikh", phone: "0322-6666666" },
    specialties: ["Penetration Testing", "Security Audits", "Incident Response", "Compliance"],
    socialMedia: { linkedin: "https://linkedin.com/company/cybersecure", twitter: "https://twitter.com/cybersecurepk" }
  },
  {
    companyName: "FinTech Innovations",
    industry: "Financial Technology",
    about: "Revolutionary fintech solutions transforming the financial services landscape.",
    vision: "Democratizing financial services through innovative technology.",
    mission: "Building secure and accessible financial technology solutions.",
    foundedYear: 2021,
    employeeCount: "11-50",
    headquartersLocation: "Karachi",
    website: "https://fintech.pk",
    companyEmail: "jobs@fintech.pk",
    contactPerson: { name: "Ayesha Malik", phone: "0334-9999999" },
    specialties: ["Blockchain", "Payment Systems", "Digital Banking", "Cryptocurrency"],
    socialMedia: { linkedin: "https://linkedin.com/company/fintech", twitter: "https://twitter.com/fintechpk" }
  },
  {
    companyName: "GameDev Studios",
    industry: "Game Development",
    about: "Creative game development studio producing engaging and immersive gaming experiences.",
    vision: "Creating world-class games that entertain and inspire players globally.",
    mission: "Developing innovative games that push the boundaries of interactive entertainment.",
    foundedYear: 2018,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://gamedev.pk",
    companyEmail: "careers@gamedev.pk",
    contactPerson: { name: "Bilal Ahmed", phone: "0315-1111111" },
    specialties: ["Unity", "Unreal Engine", "Mobile Games", "VR/AR"],
    socialMedia: { linkedin: "https://linkedin.com/company/gamedev", twitter: "https://twitter.com/gamedevpk" }
  },
  {
    companyName: "EduTech Solutions",
    industry: "Educational Technology",
    about: "Innovative educational technology solutions transforming learning experiences.",
    vision: "Revolutionizing education through technology and innovation.",
    mission: "Making quality education accessible through cutting-edge technology.",
    foundedYear: 2020,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://edutech.pk",
    companyEmail: "hr@edutech.pk",
    contactPerson: { name: "Dr. Nadia Khan", phone: "0300-2222222" },
    specialties: ["E-learning Platforms", "LMS", "Educational Apps", "Virtual Classrooms"],
    socialMedia: { linkedin: "https://linkedin.com/company/edutech", twitter: "https://twitter.com/edutechpk" }
  },
  {
    companyName: "HealthTech Innovations",
    industry: "Healthcare Technology",
    about: "Advanced healthcare technology solutions improving patient care and medical outcomes.",
    vision: "Transforming healthcare through innovative technology solutions.",
    mission: "Developing technology that enhances healthcare delivery and patient outcomes.",
    foundedYear: 2017,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://healthtech.pk",
    companyEmail: "careers@healthtech.pk",
    contactPerson: { name: "Dr. Kamran Ali", phone: "0321-3333333" },
    specialties: ["Telemedicine", "Health Apps", "Medical Software", "IoT Healthcare"],
    socialMedia: { linkedin: "https://linkedin.com/company/healthtech", twitter: "https://twitter.com/healthtechpk" }
  },
  {
    companyName: "AgriTech Solutions",
    industry: "Agricultural Technology",
    about: "Smart agriculture solutions leveraging technology to improve farming efficiency.",
    vision: "Modernizing agriculture through innovative technology solutions.",
    mission: "Empowering farmers with technology-driven agricultural solutions.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Faisalabad",
    website: "https://agritech.pk",
    companyEmail: "info@agritech.pk",
    contactPerson: { name: "Muhammad Tariq", phone: "0333-4444444" },
    specialties: ["IoT Sensors", "Precision Agriculture", "Farm Management", "Crop Monitoring"],
    socialMedia: { linkedin: "https://linkedin.com/company/agritech", twitter: "https://twitter.com/agritechpk" }
  },
  {
    companyName: "RetailTech Pro",
    industry: "Retail Technology",
    about: "Comprehensive retail technology solutions for modern commerce businesses.",
    vision: "Revolutionizing retail through innovative technology platforms.",
    mission: "Enabling retailers to thrive in the digital marketplace.",
    foundedYear: 2016,
    employeeCount: "51-200",
    headquartersLocation: "Lahore",
    website: "https://retailtech.pk",
    companyEmail: "jobs@retailtech.pk",
    contactPerson: { name: "Sana Malik", phone: "0345-5555555" },
    specialties: ["POS Systems", "Inventory Management", "E-commerce", "Customer Analytics"],
    socialMedia: { linkedin: "https://linkedin.com/company/retailtech", twitter: "https://twitter.com/retailtechpk" }
  },
  {
    companyName: "LogiTech Systems",
    industry: "Logistics Technology",
    about: "Advanced logistics and supply chain management technology solutions.",
    vision: "Optimizing global supply chains through intelligent technology.",
    mission: "Streamlining logistics operations with innovative technology solutions.",
    foundedYear: 2015,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://logitech.pk",
    companyEmail: "careers@logitech.pk",
    contactPerson: { name: "Rashid Khan", phone: "0312-6666666" },
    specialties: ["Supply Chain", "Fleet Management", "Warehouse Systems", "Route Optimization"],
    socialMedia: { linkedin: "https://linkedin.com/company/logitech", twitter: "https://twitter.com/logitechpk" }
  },
  {
    companyName: "PropTech Solutions",
    industry: "Property Technology",
    about: "Innovative property technology solutions transforming real estate industry.",
    vision: "Digitizing the real estate industry through cutting-edge technology.",
    mission: "Making property transactions seamless through technology innovation.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Islamabad",
    website: "https://proptech.pk",
    companyEmail: "hr@proptech.pk",
    contactPerson: { name: "Farah Ahmed", phone: "0301-7777777" },
    specialties: ["Property Management", "Real Estate Apps", "Virtual Tours", "CRM"],
    socialMedia: { linkedin: "https://linkedin.com/company/proptech", twitter: "https://twitter.com/proptechpk" }
  },
  {
    companyName: "MediaTech Studios",
    industry: "Media Technology",
    about: "Creative media technology solutions for digital content and entertainment.",
    vision: "Shaping the future of digital media and entertainment technology.",
    mission: "Creating innovative media solutions that engage and inspire audiences.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Lahore",
    website: "https://mediatech.pk",
    companyEmail: "careers@mediatech.pk",
    contactPerson: { name: "Usman Ali", phone: "0322-8888888" },
    specialties: ["Video Streaming", "Content Management", "Digital Marketing", "Social Media"],
    socialMedia: { linkedin: "https://linkedin.com/company/mediatech", twitter: "https://twitter.com/mediatechpk" }
  },
  {
    companyName: "AutoTech Innovations",
    industry: "Automotive Technology",
    about: "Advanced automotive technology solutions for the modern transportation industry.",
    vision: "Driving the future of automotive technology and smart mobility.",
    mission: "Developing innovative solutions for the automotive industry.",
    foundedYear: 2017,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://autotech.pk",
    companyEmail: "jobs@autotech.pk",
    contactPerson: { name: "Tariq Mahmood", phone: "0334-9999999" },
    specialties: ["Connected Cars", "Fleet Tracking", "Automotive Software", "IoT"],
    socialMedia: { linkedin: "https://linkedin.com/company/autotech", twitter: "https://twitter.com/autotechpk" }
  },
  {
    companyName: "EnergyTech Solutions",
    industry: "Energy Technology",
    about: "Sustainable energy technology solutions for a greener future.",
    vision: "Leading the transition to sustainable energy through innovation.",
    mission: "Developing clean energy solutions for environmental sustainability.",
    foundedYear: 2019,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://energytech.pk",
    companyEmail: "careers@energytech.pk",
    contactPerson: { name: "Dr. Amina Shah", phone: "0315-1010101" },
    specialties: ["Solar Systems", "Smart Grid", "Energy Management", "Renewable Energy"],
    socialMedia: { linkedin: "https://linkedin.com/company/energytech", twitter: "https://twitter.com/energytechpk" }
  },
  {
    companyName: "SportsTech Pro",
    industry: "Sports Technology",
    about: "Innovative sports technology solutions enhancing athletic performance and fan engagement.",
    vision: "Revolutionizing sports through cutting-edge technology solutions.",
    mission: "Enhancing sports experiences for athletes, teams, and fans.",
    foundedYear: 2021,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://sportstech.pk",
    companyEmail: "info@sportstech.pk",
    contactPerson: { name: "Ahmed Raza", phone: "0300-1212121" },
    specialties: ["Sports Analytics", "Performance Tracking", "Fan Engagement", "Live Streaming"],
    socialMedia: { linkedin: "https://linkedin.com/company/sportstech", twitter: "https://twitter.com/sportstechpk" }
  },
  {
    companyName: "TravelTech Solutions",
    industry: "Travel Technology",
    about: "Comprehensive travel technology solutions for the tourism and hospitality industry.",
    vision: "Transforming travel experiences through innovative technology.",
    mission: "Making travel planning and booking seamless through technology.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Karachi",
    website: "https://traveltech.pk",
    companyEmail: "hr@traveltech.pk",
    contactPerson: { name: "Sadia Khan", phone: "0321-1313131" },
    specialties: ["Booking Systems", "Travel Apps", "Hotel Management", "Tour Planning"],
    socialMedia: { linkedin: "https://linkedin.com/company/traveltech", twitter: "https://twitter.com/traveltechpk" }
  },
  {
    companyName: "FoodTech Innovations",
    industry: "Food Technology",
    about: "Revolutionary food technology solutions transforming the culinary industry.",
    vision: "Innovating the future of food through technology and creativity.",
    mission: "Enhancing food experiences through technological innovation.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://foodtech.pk",
    companyEmail: "careers@foodtech.pk",
    contactPerson: { name: "Chef Malik", phone: "0333-1414141" },
    specialties: ["Food Delivery", "Restaurant Management", "Kitchen Automation", "Food Safety"],
    socialMedia: { linkedin: "https://linkedin.com/company/foodtech", twitter: "https://twitter.com/foodtechpk" }
  },
  {
    companyName: "LegalTech Pro",
    industry: "Legal Technology",
    about: "Advanced legal technology solutions streamlining legal processes and services.",
    vision: "Modernizing the legal industry through innovative technology.",
    mission: "Making legal services more accessible and efficient through technology.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Islamabad",
    website: "https://legaltech.pk",
    companyEmail: "info@legaltech.pk",
    contactPerson: { name: "Advocate Sarah", phone: "0345-1515151" },
    specialties: ["Case Management", "Legal Research", "Document Automation", "Client Portal"],
    socialMedia: { linkedin: "https://linkedin.com/company/legaltech", twitter: "https://twitter.com/legaltechpk" }
  },
  {
    companyName: "InsurTech Solutions",
    industry: "Insurance Technology",
    about: "Innovative insurance technology solutions modernizing the insurance industry.",
    vision: "Transforming insurance through digital innovation and customer-centric solutions.",
    mission: "Making insurance more accessible and transparent through technology.",
    foundedYear: 2017,
    employeeCount: "51-200",
    headquartersLocation: "Karachi",
    website: "https://insurtech.pk",
    companyEmail: "jobs@insurtech.pk",
    contactPerson: { name: "Rizwan Ahmed", phone: "0312-1616161" },
    specialties: ["Claims Processing", "Risk Assessment", "Policy Management", "Customer Portal"],
    socialMedia: { linkedin: "https://linkedin.com/company/insurtech", twitter: "https://twitter.com/insurtechpk" }
  },
  {
    companyName: "HRTech Innovations",
    industry: "Human Resources Technology",
    about: "Comprehensive HR technology solutions optimizing human resource management.",
    vision: "Revolutionizing HR practices through innovative technology solutions.",
    mission: "Empowering HR professionals with cutting-edge technology tools.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Lahore",
    website: "https://hrtech.pk",
    companyEmail: "careers@hrtech.pk",
    contactPerson: { name: "Noor Fatima", phone: "0301-1717171" },
    specialties: ["HRIS", "Payroll Systems", "Recruitment", "Performance Management"],
    socialMedia: { linkedin: "https://linkedin.com/company/hrtech", twitter: "https://twitter.com/hrtechpk" }
  },
  {
    companyName: "MarketTech Pro",
    industry: "Marketing Technology",
    about: "Advanced marketing technology solutions driving digital marketing success.",
    vision: "Empowering businesses with data-driven marketing technology.",
    mission: "Delivering innovative marketing solutions that drive growth and engagement.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Islamabad",
    website: "https://markettech.pk",
    companyEmail: "hr@markettech.pk",
    contactPerson: { name: "Asad Malik", phone: "0322-1818181" },
    specialties: ["Marketing Automation", "CRM", "Analytics", "Social Media Management"],
    socialMedia: { linkedin: "https://linkedin.com/company/markettech", twitter: "https://twitter.com/markettechpk" }
  },
  {
    companyName: "ConstructTech Solutions",
    industry: "Construction Technology",
    about: "Innovative construction technology solutions modernizing the building industry.",
    vision: "Building the future through advanced construction technology.",
    mission: "Transforming construction processes through innovative technology solutions.",
    foundedYear: 2016,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://constructtech.pk",
    companyEmail: "jobs@constructtech.pk",
    contactPerson: { name: "Engr. Hassan", phone: "0334-1919191" },
    specialties: ["Project Management", "BIM", "Construction Software", "Site Monitoring"],
    socialMedia: { linkedin: "https://linkedin.com/company/constructtech", twitter: "https://twitter.com/constructtechpk" }
  },
  {
    companyName: "EventTech Innovations",
    industry: "Event Technology",
    about: "Comprehensive event technology solutions for seamless event management.",
    vision: "Revolutionizing event experiences through innovative technology.",
    mission: "Making event planning and execution effortless through technology.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://eventtech.pk",
    companyEmail: "info@eventtech.pk",
    contactPerson: { name: "Zainab Ali", phone: "0315-2020202" },
    specialties: ["Event Management", "Ticketing Systems", "Live Streaming", "Virtual Events"],
    socialMedia: { linkedin: "https://linkedin.com/company/eventtech", twitter: "https://twitter.com/eventtechpk" }
  },
  {
    companyName: "SecurityTech Pro",
    industry: "Security Technology",
    about: "Advanced security technology solutions protecting businesses and individuals.",
    vision: "Creating a safer world through innovative security technology.",
    mission: "Providing comprehensive security solutions through cutting-edge technology.",
    foundedYear: 2015,
    employeeCount: "101-200",
    headquartersLocation: "Islamabad",
    website: "https://securitytech.pk",
    companyEmail: "careers@securitytech.pk",
    contactPerson: { name: "Col. Retired Akram", phone: "0300-2121212" },
    specialties: ["Surveillance Systems", "Access Control", "Biometric Solutions", "Security Software"],
    socialMedia: { linkedin: "https://linkedin.com/company/securitytech", twitter: "https://twitter.com/securitytechpk" }
  },
  {
    companyName: "CleanTech Solutions",
    industry: "Clean Technology",
    about: "Sustainable clean technology solutions for environmental conservation.",
    vision: "Leading the clean technology revolution for a sustainable future.",
    mission: "Developing eco-friendly technology solutions for environmental protection.",
    foundedYear: 2021,
    employeeCount: "11-50",
    headquartersLocation: "Karachi",
    website: "https://cleantech.pk",
    companyEmail: "hr@cleantech.pk",
    contactPerson: { name: "Dr. Eco Friendly", phone: "0321-2222222" },
    specialties: ["Waste Management", "Water Treatment", "Air Purification", "Green Energy"],
    socialMedia: { linkedin: "https://linkedin.com/company/cleantech", twitter: "https://twitter.com/cleantechpk" }
  },
  {
    companyName: "VoiceTech Innovations",
    industry: "Voice Technology",
    about: "Cutting-edge voice technology solutions and AI-powered voice applications.",
    vision: "Pioneering the future of voice-enabled technology and communication.",
    mission: "Developing innovative voice solutions that enhance human-computer interaction.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://voicetech.pk",
    companyEmail: "careers@voicetech.pk",
    contactPerson: { name: "Alexa Khan", phone: "0333-2323232" },
    specialties: ["Voice Recognition", "Speech Processing", "Voice Assistants", "Audio Analytics"],
    socialMedia: { linkedin: "https://linkedin.com/company/voicetech", twitter: "https://twitter.com/voicetechpk" }
  },
  {
    companyName: "RoboTech Solutions",
    industry: "Robotics Technology",
    about: "Advanced robotics solutions for industrial automation and smart manufacturing.",
    vision: "Automating the future through intelligent robotics technology.",
    mission: "Developing robotic solutions that enhance productivity and efficiency.",
    foundedYear: 2017,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://robotech.pk",
    companyEmail: "jobs@robotech.pk",
    contactPerson: { name: "Dr. Robot Singh", phone: "0345-2424242" },
    specialties: ["Industrial Robots", "Automation", "AI Robotics", "Manufacturing Systems"],
    socialMedia: { linkedin: "https://linkedin.com/company/robotech", twitter: "https://twitter.com/robotechpk" }
  },
  {
    companyName: "BlockTech Pro",
    industry: "Blockchain Technology",
    about: "Revolutionary blockchain technology solutions for decentralized applications.",
    vision: "Building the decentralized future through blockchain innovation.",
    mission: "Developing secure and transparent blockchain solutions for various industries.",
    foundedYear: 2018,
    employeeCount: "11-50",
    headquartersLocation: "Karachi",
    website: "https://blocktech.pk",
    companyEmail: "info@blocktech.pk",
    contactPerson: { name: "Satoshi Nakamoto Jr", phone: "0312-2525252" },
    specialties: ["Smart Contracts", "DeFi", "NFT Platforms", "Cryptocurrency"],
    socialMedia: { linkedin: "https://linkedin.com/company/blocktech", twitter: "https://twitter.com/blocktechpk" }
  },
  {
    companyName: "QuantumTech Innovations",
    industry: "Quantum Technology",
    about: "Next-generation quantum technology solutions pushing the boundaries of computing.",
    vision: "Pioneering the quantum computing revolution for unprecedented computational power.",
    mission: "Developing quantum solutions that solve complex computational challenges.",
    foundedYear: 2021,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://quantumtech.pk",
    companyEmail: "careers@quantumtech.pk",
    contactPerson: { name: "Dr. Quantum Ali", phone: "0301-2626262" },
    specialties: ["Quantum Computing", "Quantum Algorithms", "Quantum Cryptography", "Research"],
    socialMedia: { linkedin: "https://linkedin.com/company/quantumtech", twitter: "https://twitter.com/quantumtechpk" }
  },
  {
    companyName: "NanoTech Solutions",
    industry: "Nanotechnology",
    about: "Advanced nanotechnology solutions for various industrial applications.",
    vision: "Exploring the microscopic world to create macroscopic innovations.",
    mission: "Developing nanotechnology solutions that revolutionize materials and processes.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Islamabad",
    website: "https://nanotech.pk",
    companyEmail: "hr@nanotech.pk",
    contactPerson: { name: "Dr. Nano Particle", phone: "0322-2727272" },
    specialties: ["Nanomaterials", "Nanoelectronics", "Bionanotechnology", "Research & Development"],
    socialMedia: { linkedin: "https://linkedin.com/company/nanotech", twitter: "https://twitter.com/nanotechpk" }
  },
  {
    companyName: "BioTech Innovations",
    industry: "Biotechnology",
    about: "Cutting-edge biotechnology solutions for healthcare and life sciences.",
    vision: "Advancing human health through biotechnology innovation.",
    mission: "Developing biotechnology solutions that improve quality of life.",
    foundedYear: 2016,
    employeeCount: "51-200",
    headquartersLocation: "Karachi",
    website: "https://biotech.pk",
    companyEmail: "careers@biotech.pk",
    contactPerson: { name: "Dr. Bio Scientist", phone: "0334-2828282" },
    specialties: ["Genetic Engineering", "Bioinformatics", "Drug Discovery", "Medical Devices"],
    socialMedia: { linkedin: "https://linkedin.com/company/biotech", twitter: "https://twitter.com/biotechpk" }
  },
  {
    companyName: "SpaceTech Pro",
    industry: "Space Technology",
    about: "Innovative space technology solutions for satellite and aerospace applications.",
    vision: "Reaching for the stars through advanced space technology.",
    mission: "Developing space technology solutions for exploration and communication.",
    foundedYear: 2020,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://spacetech.pk",
    companyEmail: "info@spacetech.pk",
    contactPerson: { name: "Astronaut Ahmed", phone: "0315-2929292" },
    specialties: ["Satellite Technology", "Aerospace Engineering", "Space Communications", "Navigation Systems"],
    socialMedia: { linkedin: "https://linkedin.com/company/spacetech", twitter: "https://twitter.com/spacetechpk" }
  },
  {
    companyName: "GreenTech Solutions",
    industry: "Green Technology",
    about: "Sustainable green technology solutions for environmental conservation and renewable energy.",
    vision: "Creating a greener planet through innovative environmental technology.",
    mission: "Developing eco-friendly solutions that protect our environment.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://greentech.pk",
    companyEmail: "jobs@greentech.pk",
    contactPerson: { name: "Green Warrior", phone: "0300-3030303" },
    specialties: ["Solar Energy", "Wind Power", "Environmental Monitoring", "Sustainable Solutions"],
    socialMedia: { linkedin: "https://linkedin.com/company/greentech", twitter: "https://twitter.com/greentechpk" }
  },
  {
    companyName: "SmartTech Innovations",
    industry: "Smart Technology",
    about: "Comprehensive smart technology solutions for intelligent automation and IoT applications.",
    vision: "Building smarter cities and homes through intelligent technology.",
    mission: "Connecting the world through smart, interconnected technology solutions.",
    foundedYear: 2017,
    employeeCount: "101-200",
    headquartersLocation: "Karachi",
    website: "https://smarttech.pk",
    companyEmail: "careers@smarttech.pk",
    contactPerson: { name: "Smart Assistant", phone: "0321-3131313" },
    specialties: ["Smart Homes", "IoT Devices", "Smart Cities", "Connected Systems"],
    socialMedia: { linkedin: "https://linkedin.com/company/smarttech", twitter: "https://twitter.com/smarttechpk" }
  },
  {
    companyName: "NeuroTech Pro",
    industry: "Neurotechnology",
    about: "Advanced neurotechnology solutions bridging the gap between brain and computer.",
    vision: "Unlocking the potential of the human brain through technology.",
    mission: "Developing neurotechnology solutions that enhance human capabilities.",
    foundedYear: 2021,
    employeeCount: "11-50",
    headquartersLocation: "Lahore",
    website: "https://neurotech.pk",
    companyEmail: "hr@neurotech.pk",
    contactPerson: { name: "Dr. Brain Power", phone: "0333-3232323" },
    specialties: ["Brain-Computer Interface", "Neural Networks", "Cognitive Enhancement", "Medical Neurotechnology"],
    socialMedia: { linkedin: "https://linkedin.com/company/neurotech", twitter: "https://twitter.com/neurotechpk" }
  },
  {
    companyName: "CryptoTech Solutions",
    industry: "Cryptocurrency Technology",
    about: "Secure cryptocurrency and digital asset technology solutions.",
    vision: "Securing the future of digital finance through cryptographic innovation.",
    mission: "Developing secure and reliable cryptocurrency technology solutions.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Islamabad",
    website: "https://cryptotech.pk",
    companyEmail: "info@cryptotech.pk",
    contactPerson: { name: "Crypto Master", phone: "0345-3333333" },
    specialties: ["Cryptocurrency Exchange", "Digital Wallets", "Blockchain Security", "DeFi Protocols"],
    socialMedia: { linkedin: "https://linkedin.com/company/cryptotech", twitter: "https://twitter.com/cryptotechpk" }
  },
  {
    companyName: "MetaTech Innovations",
    industry: "Metaverse Technology",
    about: "Immersive metaverse technology solutions creating virtual worlds and experiences.",
    vision: "Building the metaverse of tomorrow through immersive technology.",
    mission: "Creating virtual experiences that transcend physical boundaries.",
    foundedYear: 2022,
    employeeCount: "11-50",
    headquartersLocation: "Karachi",
    website: "https://metatech.pk",
    companyEmail: "careers@metatech.pk",
    contactPerson: { name: "Meta Verse", phone: "0312-3434343" },
    specialties: ["Virtual Reality", "Augmented Reality", "3D Worlds", "Avatar Systems"],
    socialMedia: { linkedin: "https://linkedin.com/company/metatech", twitter: "https://twitter.com/metatechpk" }
  },
  {
    companyName: "DroneeTech Pro",
    industry: "Drone Technology",
    about: "Advanced drone technology solutions for various commercial and industrial applications.",
    vision: "Taking innovation to new heights through drone technology.",
    mission: "Developing drone solutions that enhance efficiency and safety across industries.",
    foundedYear: 2018,
    employeeCount: "51-200",
    headquartersLocation: "Lahore",
    website: "https://dronetech.pk",
    companyEmail: "jobs@dronetech.pk",
    contactPerson: { name: "Captain Drone", phone: "0301-3535353" },
    specialties: ["Commercial Drones", "Surveillance Systems", "Delivery Drones", "Aerial Photography"],
    socialMedia: { linkedin: "https://linkedin.com/company/dronetech", twitter: "https://twitter.com/dronetechpk" }
  },
  {
    companyName: "WaterTech Solutions",
    industry: "Water Technology",
    about: "Innovative water technology solutions for purification, conservation, and management.",
    vision: "Ensuring clean water access through advanced technology solutions.",
    mission: "Developing water technology that addresses global water challenges.",
    foundedYear: 2017,
    employeeCount: "51-200",
    headquartersLocation: "Islamabad",
    website: "https://watertech.pk",
    companyEmail: "hr@watertech.pk",
    contactPerson: { name: "Aqua Expert", phone: "0322-3636363" },
    specialties: ["Water Purification", "Desalination", "Water Management", "Smart Irrigation"],
    socialMedia: { linkedin: "https://linkedin.com/company/watertech", twitter: "https://twitter.com/watertechpk" }
  },
  {
    companyName: "PrintTech Innovations",
    industry: "3D Printing Technology",
    about: "Revolutionary 3D printing technology solutions for manufacturing and prototyping.",
    vision: "Reshaping manufacturing through advanced 3D printing technology.",
    mission: "Making 3D printing accessible and efficient for all industries.",
    foundedYear: 2019,
    employeeCount: "11-50",
    headquartersLocation: "Karachi",
    website: "https://printtech.pk",
    companyEmail: "careers@printtech.pk",
    contactPerson: { name: "3D Master", phone: "0334-3737373" },
    specialties: ["3D Printing", "Rapid Prototyping", "Additive Manufacturing", "Custom Manufacturing"],
    socialMedia: { linkedin: "https://linkedin.com/company/printtech", twitter: "https://twitter.com/printtechpk" }
  },
  {
    companyName: "SolarTech Pro",
    industry: "Solar Technology",
    about: "Comprehensive solar technology solutions for renewable energy generation.",
    vision: "Powering the world with clean solar energy technology.",
    mission: "Making solar energy accessible and efficient for everyone.",
    foundedYear: 2016,
    employeeCount: "101-200",
    headquartersLocation: "Lahore",
    website: "https://solartech.pk",
    companyEmail: "info@solartech.pk",
    contactPerson: { name: "Solar Champion", phone: "0315-3838383" },
    specialties: ["Solar Panels", "Solar Systems", "Energy Storage", "Grid Integration"],
    socialMedia: { linkedin: "https://linkedin.com/company/solartech", twitter: "https://twitter.com/solartechpk" }
  }
];

async function seedCompanies() {
  try {
    console.log('🌱 Starting company seeding process...');
    
    for (let i = 0; i < companies.length; i++) {
      const companyData = companies[i];
      
      // Create user account for company
      const userEmail = companyData.companyEmail;
      const userName = companyData.companyName;
      
      // Check if user already exists
      const existingUser = await User.findOne({ email: userEmail });
      if (existingUser) {
        console.log(`⚠️  User already exists for ${userName}, skipping...`);
        continue;
      }
      
      // Create user
      const user = new User({
        name: userName,
        email: userEmail,
        password: 'Company123!', // Default password
        role: 'company',
        isVerified: true,
        isActive: true
      });
      
      await user.save();
      console.log(`✅ Created user for ${userName}`);
      
      // Create company profile
      const companyProfile = new CompanyProfile({
        userId: user._id,
        ...companyData
      });
      
      await companyProfile.save();
      console.log(`✅ Created profile for ${userName}`);
    }
    
    console.log('🎉 Company seeding completed successfully!');
    console.log(`📊 Total companies created: ${companies.length}`);
    
  } catch (error) {
    console.error('❌ Error seeding companies:', error);
  }
}

module.exports = { seedCompanies, companies };