const PDFDocument = require('pdfkit');

class UniversalPDFTemplate {
  constructor() {
    this.doc = new PDFDocument({ 
      margin: 72,
      size: 'A4',
      info: {
        Title: 'COMSATS Internship Portal Report',
        Author: 'COMSATS Internship Portal',
        Subject: 'Weekly Report',
        Creator: 'COMSATS Internship Portal'
      }
    }); // 1 inch margins
    this.pageWidth = this.doc.page.width - 144; // Account for margins
  }

  // Header section with portal branding
  addHeader() {
    // Add some top margin
    this.doc.moveDown(0.5);
    
    // Portal title with background color effect
    this.doc.fontSize(20).fillColor('#003366').font('Helvetica-Bold'); // COMSATS Blue
    this.doc.text('COMSATS INTERNSHIP PORTAL', { align: 'center' });
    
    // Subtitle
    this.doc.fontSize(10).fillColor('#6b7280').font('Helvetica');
    this.doc.text('Department of Computer Science', { align: 'center' });
    
    this.addDivider();
    this.doc.moveDown(0.5);
    return this;
  }

  // Report title (dynamic based on report type)
  addTitle(title) {
    this.doc.fontSize(16).fillColor('#003366').font('Helvetica-Bold'); // COMSATS Blue
    this.doc.text(title.toUpperCase(), { align: 'center' });
    this.doc.moveDown(1);
    this.addDivider();
    this.doc.moveDown(0.5);
    return this;
  }

  // Section with key-value pairs in table format
  addDetailsSection(details) {
    this.doc.fontSize(11).fillColor('#000000').font('Helvetica');
    
    Object.entries(details).forEach(([key, value]) => {
      if (value !== null && value !== undefined && value !== '') {
        const y = this.doc.y;
        
        // Draw left column (label)
        this.doc.fillColor('#374151').font('Helvetica-Bold');
        this.doc.text(`${key}:`, 72, y, { width: 200, align: 'left' });
        
        // Draw vertical separator line
        this.doc.strokeColor('#e5e7eb')
             .lineWidth(1)
             .moveTo(280, y - 2)
             .lineTo(280, y + 12)
             .stroke();
        
        // Draw right column (value)
        this.doc.fillColor('#000000').font('Helvetica');
        this.doc.text(value.toString(), 290, y, { width: this.pageWidth - 220, align: 'left' });
        
        this.doc.moveDown(0.8);
      }
    });
    
    this.doc.moveDown(0.5);
    return this;
  }

  // Content section with dividers
  addContentSection(title, content) {
    this.addDivider();
    this.doc.fontSize(12).fillColor('#003366').font('Helvetica-Bold'); // COMSATS Blue
    this.doc.text(`${title}:`);
    this.doc.moveDown(0.3);
    this.doc.fontSize(11).fillColor('#000000').font('Helvetica');
    
    // Enhanced content handling for edge cases
    let displayContent = 'Not specified';
    if (content && 
        content !== 'undefined' && 
        content !== 'null' && 
        content !== null && 
        content !== undefined && 
        content.toString().trim() !== '') {
      displayContent = content.toString().trim();
    }
    
    this.doc.text(displayContent, { 
      width: this.pageWidth - 20,
      align: 'justify'
    });
    this.doc.moveDown(0.8);
    return this;
  }

  // List section with bullet points
  addListSection(title, items) {
    this.addDivider();
    this.doc.fontSize(12).fillColor('#003366').font('Helvetica-Bold'); // COMSATS Blue
    this.doc.text(`${title}:`);
    this.doc.moveDown(0.3);
    this.doc.fontSize(11).fillColor('#000000').font('Helvetica');
    
    if (Array.isArray(items) && items.length > 0) {
      items.forEach(item => {
        this.doc.text(`• ${item}`, { indent: 20 });
      });
    } else if (typeof items === 'string' && items.trim()) {
      const listItems = items.split(/[\n•]/).filter(item => item.trim());
      listItems.forEach(item => {
        this.doc.text(`• ${item.trim()}`, { indent: 20 });
      });
    } else {
      this.doc.text('• Not specified', { indent: 20 });
    }
    
    this.doc.moveDown(0.8);
    return this;
  }

  // Add horizontal divider
  addDivider() {
    const currentY = this.doc.y;
    this.doc.strokeColor('#e5e7eb')
         .lineWidth(1)
         .moveTo(72, currentY + 5)
         .lineTo(this.doc.page.width - 72, currentY + 5)
         .stroke();
    this.doc.moveDown(0.3);
    return this;
  }

  // Add footer
  addFooter(pageNumber = 1) {
    const footerY = this.doc.page.height - 50;
    this.doc.fontSize(9).fillColor('#6b7280').font('Helvetica');
    this.doc.text(
      `Generated by COMSATS Internship Portal - ${new Date().toLocaleDateString()}`,
      72,
      footerY,
      { width: this.pageWidth / 2, align: 'left' }
    );
    this.doc.text(
      `Page ${pageNumber}`,
      72 + this.pageWidth / 2,
      footerY,
      { width: this.pageWidth / 2, align: 'right' }
    );
    return this;
  }

  // Get the PDF document
  getDocument() {
    return this.doc;
  }

  // Finalize the PDF
  finalize() {
    this.addFooter();
    this.doc.end();
    return this.doc;
  }
}

module.exports = { UniversalPDFTemplate };